return function()
	-- reset
	beforeEach(function() end)

	afterEach(function() end)

	it("test lshift", function()
		local FlagEnum = require(game.ReplicatedStorage.Packages.FlagEnum)
		local enum = FlagEnum.new()
		enum.A = enum.LShift(0)
		enum.B = enum.LShift(1)
		expect(enum.LShift(0)).to.be.equal(1)
		expect(enum.LShift(1)).to.be.equal(2)
		expect(enum.LShift(2)).to.be.equal(4)
		expect(enum.LShift(3)).to.be.equal(8)
		expect(enum.LShift(37)).to.be.equal(0)
	end)

	it("test bor", function()
		local FlagEnum = require(game.ReplicatedStorage.Packages.FlagEnum)
		local enum = FlagEnum.new()
		enum.A = enum.LShift(0)
		enum.B = enum.LShift(1)
		enum.C = enum.LShift(2)
		local bor = enum.Bor(enum.A, enum.B, enum.C)
		expect(bor).to.be.equal(0b00000111)
	end)

	it("test has flag", function()
		local FlagEnum = require(game.ReplicatedStorage.Packages.FlagEnum)
		local enum = FlagEnum.new()
		enum.A = enum.LShift(0)
		enum.B = enum.LShift(1)
		enum.C = enum.LShift(2)
		local bor = enum.Bor(enum.A, enum.B, enum.C)
		expect(enum.HasFalg(bor, enum.A)).to.ok()
		expect(enum.HasFalg(bor, enum.B)).to.ok()
		expect(enum.HasFalg(bor, enum.C)).to.ok()
		local bor2 = enum.Bor(enum.A, enum.C)
		expect(enum.HasFalg(bor, bor2)).to.ok()
	end)
end
